### ISSUE TITLE
Question: Best Practice for Removing Event Listeners after Delegation

### ISSUE THREAD

**Issue by ranchodeluxe** [jarofghosts/dom-delegation-stream#1]
Hello,
I'm interested in trying out client-side NodeJS streams and came across your [informative article](http://words.jessekeane.me/front-end-streams/). But from examining the code here i don't see how you'll ever be able to call `removeEventListener` for an element.

How do you handle unregistering an event listener when using this module? 

I forked, modified and [created a passing test](https://github.com/thebigspoon/dom-delegation-stream/commit/c4bbb03245ad98644049ca38625d6ce1163354c9) for how I would do it. But maybe you have better ideas or other small modules you use? 

Thanks for your input

**Comment by jarofghosts** [comment]
that way works. my plan is to, once i have addressed #2 , make this module better by removing the listener when `.end()` is called. that gives you a way to tear it down, and it preserves stream mechanics in what feels to be a predictable manner.
